server:
  port: 8081
  servlet:
    context-path: /booking

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bookingdb"
    username: admin1
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
