server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/account_service"
    username: admin1
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: "/F1P+ARvkjHXeNjU/h3jPTDvEy9ZqURUzXELYrD9qKV99NY0w6kp+uly68PiFVCO\n"
  valid-duration: 15 # in second
  refreshable-duration: 120 # in seconds
